# Generated by Django 5.0.2 on 2024-02-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_coverimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverimage',
            name='image',
            field=models.ImageField(upload_to='group_covers/'),
        ),
    ]
