# Generated by Django 5.0.2 on 2024-02-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_coverimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='group_covers/'),
        ),
        migrations.DeleteModel(
            name='CoverImage',
        ),
    ]
