# Generated by Django 5.0.2 on 2024-02-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_groups_cover_image_delete_coverimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='test')),
            ],
        ),
    ]
