# Generated by Django 5.0.2 on 2024-02-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_cover_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cover_Image',
        ),
    ]
