# Generated by Django 5.0.2 on 2024-02-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_delete_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='cover_image',
        ),
    ]
