# Generated by Django 5.0.2 on 2024-02-18 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_groups_cover_image_groups_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='image',
            new_name='cover_image',
        ),
    ]
