# Generated by Django 5.0.2 on 2024-02-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_image_groups_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='cover_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
