# Generated by Django 5.0.2 on 2024-02-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_imagemessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageMessage',
        ),
    ]
