# Generated by Django 5.0.2 on 2024-02-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
